org.gradle.daemon=false
org.gradle.jvmargs=-Xmx12g -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -Dfile.encoding=UTF-8
org.gradle.workers.max=8
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.configuration-cache.problems=warn

kotlin.daemon.jvmargs=-Xmx8g -XX:+UseG1GC -Dfile.encoding=UTF-8

kotlin.incremental=false
